# https://besu.hyperledger.org/stable/public-networks/reference/cli/options

# node
network = "dev"
host-allowlist = ["*"]
miner-enabled = true
miner-coinbase = "0x28fb346214e844775650718c694a83de2e109644"
min-gas-price = 0
#logging="INFO" ## default

# jsonrpc http
rpc-http-enabled = true
rpc-http-host = "0.0.0.0"
#rpc-http-port=8545 ## default
rpc-http-api = [
  "ETH",
  "NET",
  "WEB3",
  "ADMIN",
  "DEBUG",
  "EEA",
  "IBFT",
  "PERM",
  "PRIV",
  "QBFT",
]
rpc-http-cors-origins = ["*"]

# jsonrpc ws
rpc-ws-enabled = true
rpc-ws-host = "0.0.0.0"
#rpc-ws-port=8546 ## default
rpc-ws-api = [
  "ETH",
  "NET",
  "WEB3",
  "ADMIN",
  "DEBUG",
  "EEA",
  "IBFT",
  "PERM",
  "PRIV",
  "QBFT",
]

# graphql http
#graphql-http-enabled=false ## default
#graphql-http-host="0.0.0.0"
#graphql-http-port=8547 #default
#graphql-http-cors-origins=["*"]
