services:
  besu-dev:
    image: hyperledger/besu:${TAG:-latest}
    container_name: besu-dev
    configs:
      - source: config.toml
        target: /opt/besu/config.toml
    ports:
      - "127.0.0.1:8545:8545" # rpc http
      - "127.0.0.1:8546:8546" # rpc ws
      - "127.0.0.1:8547:8547" # graphql
    command: ["--config-file=/opt/besu/config.toml"]

configs:
  config.toml:
    file: ./config.toml
