services:
  besu-dev:
    image: hyperledger/besu:${TAG:-23.10.0}
    container_name: besu-dev
    configs:
      - source: config.toml
        target: /opt/besu/config.toml
    ports:
      - "127.0.0.1:8545:8545" # rpc-http
      - "127.0.0.1:8546:8546" # rpc-ws
      - "127.0.0.1:8547:8547" # graphql-http
    command: [
        "--config-file=/opt/besu/config.toml",
        # "--rpc-http-host=0.0.0.0", # bug: config.toml value is ignored
        # "--rpc-ws-host=0.0.0.0", # bug: config.toml value is ignored
        # "--graphql-http-host=0.0.0.0", # bug: config.toml value is ignored
      ]

configs:
  config.toml:
    file: ./config.toml
